// Auto-generated content data for the Bakify waitlist resource hub.
// Edit the source markdown in /content (project docs) and regenerate if you want to change this.
const STATE_LAWS = [
  {
    "state": "Alabama",
    "permit": "No state permit; food-safety course certificate + sample label submitted to county health dept",
    "cap": "None",
    "products": "Non-perishable only: no custard, whipped topping, cheesecake",
    "channels": "Direct sales, farmers markets, roadside stands, in-state mail; not restaurants/retail",
    "label": "&quot;Not inspected by the health department&quot; statement, allergen statement ≥10pt type",
    "inspectTrain": "Food-safety course required (Extension/ANSI)",
    "sources": "<a href=\"https://www.alabamapublichealth.gov/foodsafety/assets/cottagefoodlawfaqs.pdf\">ADPH FAQ</a>, <a href=\"https://www.aces.edu/blog/topics/cottage-food-law/alabama-cottage-food-law-basic-rules-and-regulations/\">ACES</a>, <a href=\"https://forrager.com/law/alabama/\">Forrager</a>",
    "details": "Permit: No state permit; food-safety course certificate + sample label submitted to county health dept. Cap: None. Products: Non-perishable only: no custard, whipped topping, cheesecake. Channels: Direct sales, farmers markets, roadside stands, in-state mail; not restaurants/retail. Label: &quot;Not inspected by the health department&quot; statement, allergen statement ≥10pt type. Inspect/Train: Food-safety course required (Extension/ANSI). Sources: <a href=\"https://www.alabamapublichealth.gov/foodsafety/assets/cottagefoodlawfaqs.pdf\">ADPH FAQ</a>, <a href=\"https://www.aces.edu/blog/topics/cottage-food-law/alabama-cottage-food-law-basic-rules-and-regulations/\">ACES</a>, <a href=\"https://forrager.com/law/alabama/\">Forrager</a>"
  },
  {
    "state": "Alaska",
    "permit": "No permit/inspection; state business license required",
    "cap": "None (removed by HB 251, Aug. 2024)",
    "products": "Non-hazardous baked goods free; potentially-hazardous items (cheesecake) direct-to-consumer only",
    "channels": "Own retail location, agent location (non-hazardous only), online",
    "label": "Disclosure re: home kitchen, unregulated except meat, allergens",
    "inspectTrain": "None required",
    "sources": "<a href=\"https://dec.alaska.gov/eh/fss/homemade-food/requirements/\">AK DEC</a>, <a href=\"https://forrager.com/law/alaska/\">Forrager</a>",
    "details": "Permit: No permit/inspection; state business license required. Cap: None (removed by HB 251, Aug. 2024). Products: Non-hazardous baked goods free; potentially-hazardous items (cheesecake) direct-to-consumer only. Channels: Own retail location, agent location (non-hazardous only), online. Label: Disclosure re: home kitchen, unregulated except meat, allergens. Inspect/Train: None required. Sources: <a href=\"https://dec.alaska.gov/eh/fss/homemade-food/requirements/\">AK DEC</a>, <a href=\"https://forrager.com/law/alaska/\">Forrager</a>"
  },
  {
    "state": "Arizona",
    "permit": "Free online registration + ANSI food-handler course, renew every 3 yrs",
    "cap": "None",
    "products": "Non-hazardous only: no custards, cream/custard fillings, meringues, cheesecake",
    "channels": "Broad: farmers markets, retail stores, restaurants, in-state online (no interstate shipping)",
    "label": "Registration #, &quot;not subject to public health inspection&quot; + pet-allergen note",
    "inspectTrain": "ANSI course required",
    "sources": "<a href=\"https://www.azdhs.gov/preparedness/epidemiology-disease-control/food-safety-environmental-services/cottage-food-program/index.php\">AZDHS</a>, <a href=\"https://www.azleg.gov/ars/36/00932.htm\">A.R.S. §36-932</a>, <a href=\"https://forrager.com/law/arizona/\">Forrager</a>",
    "details": "Permit: Free online registration + ANSI food-handler course, renew every 3 yrs. Cap: None. Products: Non-hazardous only: no custards, cream/custard fillings, meringues, cheesecake. Channels: Broad: farmers markets, retail stores, restaurants, in-state online (no interstate shipping). Label: Registration #, &quot;not subject to public health inspection&quot; + pet-allergen note. Inspect/Train: ANSI course required. Sources: <a href=\"https://www.azdhs.gov/preparedness/epidemiology-disease-control/food-safety-environmental-services/cottage-food-program/index.php\">AZDHS</a>, <a href=\"https://www.azleg.gov/ars/36/00932.htm\">A.R.S. §36-932</a>, <a href=\"https://forrager.com/law/arizona/\">Forrager</a>"
  },
  {
    "state": "Arkansas",
    "permit": "None (Food Freedom Act/Act 1040 of 2021)",
    "cap": "None",
    "products": "Non-TCS baked goods (pH ≤4.6 or water activity ≤0.85): no cheesecake/cream pies/custard",
    "channels": "Direct sales, third-party retailers (with separation from inspected goods), commercial carrier/mail; not restaurants",
    "label": "&quot;Produced in a private residence exempt from state licensing and inspection&quot; + allergen note",
    "inspectTrain": "None",
    "sources": "<a href=\"https://healthy.arkansas.gov/wp-content/uploads/Homemade-Food-Guide-5.21.2026-Update.pdf\">AR DOH Guide</a>, <a href=\"https://forrager.com/law/arkansas/\">Forrager</a>",
    "details": "Permit: None (Food Freedom Act/Act 1040 of 2021). Cap: None. Products: Non-TCS baked goods (pH ≤4.6 or water activity ≤0.85): no cheesecake/cream pies/custard. Channels: Direct sales, third-party retailers (with separation from inspected goods), commercial carrier/mail; not restaurants. Label: &quot;Produced in a private residence exempt from state licensing and inspection&quot; + allergen note. Inspect/Train: None. Sources: <a href=\"https://healthy.arkansas.gov/wp-content/uploads/Homemade-Food-Guide-5.21.2026-Update.pdf\">AR DOH Guide</a>, <a href=\"https://forrager.com/law/arkansas/\">Forrager</a>"
  },
  {
    "state": "California",
    "permit": "Class A = self-certify/register (county), no inspection. Class B = permit + mandatory home-kitchen inspection",
    "cap": "Statutory base $75K (A)/$150K (B), CPI-adjusted annually: secondary estimates <del>$86–88K (A)/</del>$172–176K (B) but <strong>[UNCONFIRMED]</strong> exact current-year figure; verify with your county Environmental Health Dept",
    "products": "Non-PHF baked goods; cream/custard/meat fillings excluded (meringue/custard pies actually excluded from the law entirely, treated as PHF)",
    "channels": "Class A direct-to-public only; Class B adds retail stores/restaurants (wholesale)",
    "label": "County name, permit/reg #, home-kitchen disclosure",
    "inspectTrain": "Approved training required within 3 months; Class B adds kitchen inspection",
    "sources": "<a href=\"https://www.cdph.ca.gov/Programs/CEH/DFDCS/Pages/FDBPrograms/FoodSafetyProgram/CottageFoodOperations.aspx\">CDPH</a>, <a href=\"https://law.justia.com/codes/california/code-hsc/division-104/part-7/chapter-2/section-113758/\">Cal. H&amp;S Code §113758</a>, <a href=\"https://forrager.com/law/california/\">Forrager</a>",
    "details": "Permit: Class A = self-certify/register (county), no inspection. Class B = permit + mandatory home-kitchen inspection. Cap: Statutory base $75K (A)/$150K (B), CPI-adjusted annually: secondary estimates <del>$86–88K (A)/</del>$172–176K (B) but <strong>[UNCONFIRMED]</strong> exact current-year figure; verify with your county Environmental Health Dept. Products: Non-PHF baked goods; cream/custard/meat fillings excluded (meringue/custard pies actually excluded from the law entirely, treated as PHF). Channels: Class A direct-to-public only; Class B adds retail stores/restaurants (wholesale). Label: County name, permit/reg #, home-kitchen disclosure. Inspect/Train: Approved training required within 3 months; Class B adds kitchen inspection. Sources: <a href=\"https://www.cdph.ca.gov/Programs/CEH/DFDCS/Pages/FDBPrograms/FoodSafetyProgram/CottageFoodOperations.aspx\">CDPH</a>, <a href=\"https://law.justia.com/codes/california/code-hsc/division-104/part-7/chapter-2/section-113758/\">Cal. H&amp;S Code §113758</a>, <a href=\"https://forrager.com/law/california/\">Forrager</a>"
  },
  {
    "state": "Colorado",
    "permit": "No license; food-safety training required (CSU Extension/food-handler card/local course)",
    "cap": "No overall cap, but $10,000/year per individual product type",
    "products": "Non-PHF; buttercream must use ghee/veg oil, not dairy; no cream/custard/meringue fillings, cream or pumpkin/sweet-potato pies",
    "channels": "Direct producer-to-consumer only (home, markets, events, in-state online); not restaurants/retail/consignment",
    "label": "Producer contact, production date, &quot;not subject to state licensure or inspection...not intended for resale.&quot;",
    "inspectTrain": "Training required. Note: a 2026 bill (&quot;Tamale Act,&quot; HB26-1033) expands allowed foods starting Jan 1, 2027: not yet in effect",
    "sources": "<a href=\"https://cdphe.colorado.gov/dehs/cottage-foods\">CDPHE</a>, <a href=\"https://forrager.com/law/colorado/\">Forrager</a>",
    "details": "Permit: No license; food-safety training required (CSU Extension/food-handler card/local course). Cap: No overall cap, but $10,000/year per individual product type. Products: Non-PHF; buttercream must use ghee/veg oil, not dairy; no cream/custard/meringue fillings, cream or pumpkin/sweet-potato pies. Channels: Direct producer-to-consumer only (home, markets, events, in-state online); not restaurants/retail/consignment. Label: Producer contact, production date, &quot;not subject to state licensure or inspection...not intended for resale.&quot; Inspect/Train: Training required. Note: a 2026 bill (&quot;Tamale Act,&quot; HB26-1033) expands allowed foods starting Jan 1, 2027: not yet in effect. Sources: <a href=\"https://cdphe.colorado.gov/dehs/cottage-foods\">CDPHE</a>, <a href=\"https://forrager.com/law/colorado/\">Forrager</a>"
  },
  {
    "state": "Connecticut",
    "permit": "Cottage Food Operator license ($50/yr, capped $100) <strong>including home kitchen inspection</strong>, renewed annually (expires Feb 28)",
    "cap": "$50,000/year",
    "products": "Non-perishable (most pies except pumpkin); perishable/refrigerated items prohibited",
    "channels": "Direct in-state only: no shipping/mail/3rd-party courier",
    "label": "Business name/home address, ingredients/allergens, disclaimer wording <strong>[UNCONFIRMED exact text: verify against official Cottage Food Manual PDF]</strong>",
    "inspectTrain": "Home kitchen inspection + ServSafe/equivalent course",
    "sources": "<a href=\"https://portal.ct.gov/dcp/cottage-foods\">CT DCP</a>, <a href=\"https://portal.ct.gov/-/media/dcp/news-releases-from-the-department-of-consumer-protection/cottage_food_manual.pdf\">Cottage Food Manual PDF</a>, <a href=\"https://forrager.com/law/connecticut/\">Forrager</a>",
    "details": "Permit: Cottage Food Operator license ($50/yr, capped $100) <strong>including home kitchen inspection</strong>, renewed annually (expires Feb 28). Cap: $50,000/year. Products: Non-perishable (most pies except pumpkin); perishable/refrigerated items prohibited. Channels: Direct in-state only: no shipping/mail/3rd-party courier. Label: Business name/home address, ingredients/allergens, disclaimer wording <strong>[UNCONFIRMED exact text: verify against official Cottage Food Manual PDF]</strong>. Inspect/Train: Home kitchen inspection + ServSafe/equivalent course. Sources: <a href=\"https://portal.ct.gov/dcp/cottage-foods\">CT DCP</a>, <a href=\"https://portal.ct.gov/-/media/dcp/news-releases-from-the-department-of-consumer-protection/cottage_food_manual.pdf\">Cottage Food Manual PDF</a>, <a href=\"https://forrager.com/law/connecticut/\">Forrager</a>"
  },
  {
    "state": "Delaware",
    "permit": "Registration ($30/yr) + pre-op home-kitchen inspection + 8-hour food-safety course (~$175)",
    "cap": "None (prior $25K cap removed ~Dec 2023)",
    "products": "Non-PHF (breads, cakes, cookies, fruit pies); no time/temperature-control items",
    "channels": "Direct sales only, in-state: <strong>online sales, retail, and wholesale prohibited</strong>",
    "label": "Town/city + &quot;Delaware,&quot; ingredients/allergens, net weight, production date/lot #, &quot;NOT subject to routine Government Food Safety Inspections&quot; (≥10pt)",
    "inspectTrain": "Pre-op inspection + 8-hr course required",
    "sources": "<a href=\"https://regulations.delaware.gov/AdminCode/title16/Department%20of%20Health%20and%20Social%20Services/Division%20of%20Public%20Health/Health%20Systems%20Protection%20(HSP)/4458A.shtml\">DE Admin Code §4458A</a>, <a href=\"https://forrager.com/law/delaware/\">Forrager</a>",
    "details": "Permit: Registration ($30/yr) + pre-op home-kitchen inspection + 8-hour food-safety course (~$175). Cap: None (prior $25K cap removed ~Dec 2023). Products: Non-PHF (breads, cakes, cookies, fruit pies); no time/temperature-control items. Channels: Direct sales only, in-state: <strong>online sales, retail, and wholesale prohibited</strong>. Label: Town/city + &quot;Delaware,&quot; ingredients/allergens, net weight, production date/lot #, &quot;NOT subject to routine Government Food Safety Inspections&quot; (≥10pt). Inspect/Train: Pre-op inspection + 8-hr course required. Sources: <a href=\"https://regulations.delaware.gov/AdminCode/title16/Department%20of%20Health%20and%20Social%20Services/Division%20of%20Public%20Health/Health%20Systems%20Protection%20(HSP)/4458A.shtml\">DE Admin Code §4458A</a>, <a href=\"https://forrager.com/law/delaware/\">Forrager</a>"
  },
  {
    "state": "Florida",
    "permit": "None: explicitly exempt (Fla. Stat. §500.80)",
    "cap": "$250,000/year (2021 Home Sweet Home Act)",
    "products": "Non-refrigerated only: no custard, cream cheese icing/filling",
    "channels": "Direct-to-consumer in person/events + in-state USPS/commercial mail; wholesale/consignment prohibited",
    "label": "Operation name/address, ingredients by weight, net weight, allergens, &quot;not subject to Florida&#39;s food safety regulations.&quot;",
    "inspectTrain": "None",
    "sources": "<a href=\"https://www.leg.state.fl.us/statutes/index.cfm?App_mode=Display_Statute&URL=0500-0599%2F0500%2FSections%2F0500.80.html\">Fla. Stat. §500.80</a>, <a href=\"https://ask.ifas.ufl.edu/publication/FS425\">UF/IFAS FS425</a>, <a href=\"https://forrager.com/law/florida/\">Forrager</a>",
    "details": "Permit: None: explicitly exempt (Fla. Stat. §500.80). Cap: $250,000/year (2021 Home Sweet Home Act). Products: Non-refrigerated only: no custard, cream cheese icing/filling. Channels: Direct-to-consumer in person/events + in-state USPS/commercial mail; wholesale/consignment prohibited. Label: Operation name/address, ingredients by weight, net weight, allergens, &quot;not subject to Florida&#39;s food safety regulations.&quot; Inspect/Train: None. Sources: <a href=\"https://www.leg.state.fl.us/statutes/index.cfm?App_mode=Display_Statute&URL=0500-0599%2F0500%2FSections%2F0500.80.html\">Fla. Stat. §500.80</a>, <a href=\"https://ask.ifas.ufl.edu/publication/FS425\">UF/IFAS FS425</a>, <a href=\"https://forrager.com/law/florida/\">Forrager</a>"
  },
  {
    "state": "Georgia",
    "permit": "No license; ANSI/ANAB food-safety course + ID-number registration (tracking only)",
    "cap": "None",
    "products": "Non-PHF (loaf breads, rolls, biscuits, cakes, cookies); no cream cheese frosting/custards",
    "channels": "Expanded by <strong>HB 398 (eff. 7/1/2025)</strong>: farmers markets, events, in-state online, <strong>and now retail stores</strong>; wholesale-to-restaurants status <strong>[UNCONFIRMED: state page says labeling/rules still &quot;Under Revision&quot; post-HB 398]</strong>",
    "label": "Business name/address or ag-dept ID, &quot;exempt from state inspection...may contain allergens&quot;: wording provisional per above",
    "inspectTrain": "One-time ANSI/ANAB course",
    "sources": "<a href=\"https://www.agr.georgia.gov/cottage-food\">GA Dept. of Ag</a>, <a href=\"https://rules.sos.ga.gov/gac/40-7-19\">GAC 40-7-19</a>, <a href=\"https://forrager.com/law/georgia/\">Forrager</a>",
    "details": "Permit: No license; ANSI/ANAB food-safety course + ID-number registration (tracking only). Cap: None. Products: Non-PHF (loaf breads, rolls, biscuits, cakes, cookies); no cream cheese frosting/custards. Channels: Expanded by <strong>HB 398 (eff. 7/1/2025)</strong>: farmers markets, events, in-state online, <strong>and now retail stores</strong>; wholesale-to-restaurants status <strong>[UNCONFIRMED: state page says labeling/rules still &quot;Under Revision&quot; post-HB 398]</strong>. Label: Business name/address or ag-dept ID, &quot;exempt from state inspection...may contain allergens&quot;: wording provisional per above. Inspect/Train: One-time ANSI/ANAB course. Sources: <a href=\"https://www.agr.georgia.gov/cottage-food\">GA Dept. of Ag</a>, <a href=\"https://rules.sos.ga.gov/gac/40-7-19\">GAC 40-7-19</a>, <a href=\"https://forrager.com/law/georgia/\">Forrager</a>"
  },
  {
    "state": "Hawaii",
    "permit": "None to start; food safety training required (DOH or ANSI, valid 3 yrs)",
    "cap": "None found",
    "products": "No custard/cream fillings",
    "channels": "Events/farmers markets/online confirmed; retail/mail-order claims <strong>[UNCONFIRMED]</strong>",
    "label": "Home-kitchen disclosure, ingredients, allergens, contact",
    "inspectTrain": "Training yes, inspection no (DOH retains authority)",
    "sources": "<a href=\"https://health.hawaii.gov/san/files/2019/09/hmf-foods-01.29.2026.pdf\">HI DOH PDF</a>, <a href=\"https://forrager.com/law/hawaii/\">Forrager</a>",
    "details": "Permit: None to start; food safety training required (DOH or ANSI, valid 3 yrs). Cap: None found. Products: No custard/cream fillings. Channels: Events/farmers markets/online confirmed; retail/mail-order claims <strong>[UNCONFIRMED]</strong>. Label: Home-kitchen disclosure, ingredients, allergens, contact. Inspect/Train: Training yes, inspection no (DOH retains authority). Sources: <a href=\"https://health.hawaii.gov/san/files/2019/09/hmf-foods-01.29.2026.pdf\">HI DOH PDF</a>, <a href=\"https://forrager.com/law/hawaii/\">Forrager</a>"
  },
  {
    "state": "Idaho",
    "permit": "None",
    "cap": "None",
    "products": "Non-perishable only: no refrigerated/cream/custard fillings",
    "channels": "Direct sales, farmers markets, online/mail; 3rd-party retail needs a real permit",
    "label": "Owner contact, allergen disclosure, home-kitchen disclaimer (wording varies)",
    "inspectTrain": "None",
    "sources": "<a href=\"https://phd5.idaho.gov/Documents/Environmental-Health/Cottage-Food-FAQs_2-16-17.pdf\">ID public health FAQ</a>, <a href=\"https://ij.org/issues/economic-liberty/homemade-food-seller/idaho/\">IJ.org</a>, <a href=\"https://forrager.com/law/idaho/\">Forrager</a>",
    "details": "Permit: None. Cap: None. Products: Non-perishable only: no refrigerated/cream/custard fillings. Channels: Direct sales, farmers markets, online/mail; 3rd-party retail needs a real permit. Label: Owner contact, allergen disclosure, home-kitchen disclaimer (wording varies). Inspect/Train: None. Sources: <a href=\"https://phd5.idaho.gov/Documents/Environmental-Health/Cottage-Food-FAQs_2-16-17.pdf\">ID public health FAQ</a>, <a href=\"https://ij.org/issues/economic-liberty/homemade-food-seller/idaho/\">IJ.org</a>, <a href=\"https://forrager.com/law/idaho/\">Forrager</a>"
  },
  {
    "state": "Illinois",
    "permit": "Annual local health-dept registration, fee ≤$50 (eff. 1/1/2025)",
    "cap": "None (removed 2025)",
    "products": "Non-perishable only; perishable-filled pies prohibited",
    "channels": "Farmers markets, events, online, pickup/delivery: not retail/restaurants",
    "label": "Operation name/location, reg #, processing date, health warning",
    "inspectTrain": "Must be a <strong>certified food protection manager</strong>",
    "sources": "<a href=\"https://www.ilga.gov/Legislation/publicacts/view/103-0903\">PA 103-0903</a>, <a href=\"https://dph.illinois.gov/topics-services/food-safety/cottage-food.html\">IDPH</a>, <a href=\"https://forrager.com/law/illinois/\">Forrager</a>",
    "details": "Permit: Annual local health-dept registration, fee ≤$50 (eff. 1/1/2025). Cap: None (removed 2025). Products: Non-perishable only; perishable-filled pies prohibited. Channels: Farmers markets, events, online, pickup/delivery: not retail/restaurants. Label: Operation name/location, reg #, processing date, health warning. Inspect/Train: Must be a <strong>certified food protection manager</strong>. Sources: <a href=\"https://www.ilga.gov/Legislation/publicacts/view/103-0903\">PA 103-0903</a>, <a href=\"https://dph.illinois.gov/topics-services/food-safety/cottage-food.html\">IDPH</a>, <a href=\"https://forrager.com/law/illinois/\">Forrager</a>"
  },
  {
    "state": "Indiana",
    "permit": "None (Home Based Vendor)",
    "cap": "<strong>[UNCONFIRMED: a &quot;$1.5M&quot; figure appears in only one unreliable source]</strong>",
    "products": "Non-perishable only; no cream/pumpkin pie",
    "channels": "Direct-to-consumer in-state only: no wholesale/retail",
    "label": "Name/address, net weight, disclaimer re: uninspected production area",
    "inspectTrain": "ANSI food handler cert required; complaint-driven inspection only",
    "sources": "<a href=\"https://pickyourown.org/CottageFoodLaws-Indiana.php\">pickyourown.org</a>, <a href=\"https://ag.purdue.edu/department/foodsci/home-based-vendors.html\">Purdue Extension</a>, <a href=\"https://forrager.com/law/indiana/\">Forrager</a>",
    "details": "Permit: None (Home Based Vendor). Cap: <strong>[UNCONFIRMED: a &quot;$1.5M&quot; figure appears in only one unreliable source]</strong>. Products: Non-perishable only; no cream/pumpkin pie. Channels: Direct-to-consumer in-state only: no wholesale/retail. Label: Name/address, net weight, disclaimer re: uninspected production area. Inspect/Train: ANSI food handler cert required; complaint-driven inspection only. Sources: <a href=\"https://pickyourown.org/CottageFoodLaws-Indiana.php\">pickyourown.org</a>, <a href=\"https://ag.purdue.edu/department/foodsci/home-based-vendors.html\">Purdue Extension</a>, <a href=\"https://forrager.com/law/indiana/\">Forrager</a>"
  },
  {
    "state": "Iowa",
    "permit": "None (base tier); separate licensed HFPE tier for broader allowances",
    "cap": "None found",
    "products": "Non-perishable only",
    "channels": "Direct sales, farmers markets, home, online, producer-run temp establishments",
    "label": "Business contact, ingredients/allergens, exemption disclosure wording <strong>[UNCONFIRMED]</strong>",
    "inspectTrain": "None for base tier",
    "sources": "<a href=\"https://dial.iowa.gov/licenses/food-establishments-hotels/cottage-food-law\">Iowa DIAL</a>, <a href=\"https://forrager.com/law/iowa/\">Forrager</a>",
    "details": "Permit: None (base tier); separate licensed HFPE tier for broader allowances. Cap: None found. Products: Non-perishable only. Channels: Direct sales, farmers markets, home, online, producer-run temp establishments. Label: Business contact, ingredients/allergens, exemption disclosure wording <strong>[UNCONFIRMED]</strong>. Inspect/Train: None for base tier. Sources: <a href=\"https://dial.iowa.gov/licenses/food-establishments-hotels/cottage-food-law\">Iowa DIAL</a>, <a href=\"https://forrager.com/law/iowa/\">Forrager</a>"
  },
  {
    "state": "Kansas",
    "permit": "None: exempt under K.S.A. §65-689(d)(4)",
    "cap": "None found",
    "products": "Not officially enumerated; functionally non-perishable only",
    "channels": "Direct to consumer (statute doesn&#39;t list full venues)",
    "label": "<strong>[UNCONFIRMED: no official page with exact wording found; recommend calling KDA Food Safety &amp; Lodging directly, 785-564-6767]</strong>",
    "inspectTrain": "None found",
    "sources": "<a href=\"https://www.agriculture.ks.gov/divisions-programs/food-safety-and-lodging/laws-regulations-code-for-food-safety-lodging\">KDA</a>, <a href=\"https://nationalaglawcenter.org/wp-content/uploads/assets/cottagefood/Kansas.pdf\">Nat&#39;l Ag Law Center</a>, <a href=\"https://forrager.com/law/kansas/\">Forrager</a>",
    "details": "Permit: None: exempt under K.S.A. §65-689(d)(4). Cap: None found. Products: Not officially enumerated; functionally non-perishable only. Channels: Direct to consumer (statute doesn&#39;t list full venues). Label: <strong>[UNCONFIRMED: no official page with exact wording found; recommend calling KDA Food Safety &amp; Lodging directly, 785-564-6767]</strong>. Inspect/Train: None found. Sources: <a href=\"https://www.agriculture.ks.gov/divisions-programs/food-safety-and-lodging/laws-regulations-code-for-food-safety-lodging\">KDA</a>, <a href=\"https://nationalaglawcenter.org/wp-content/uploads/assets/cottagefood/Kansas.pdf\">Nat&#39;l Ag Law Center</a>, <a href=\"https://forrager.com/law/kansas/\">Forrager</a>"
  },
  {
    "state": "Kentucky",
    "permit": "DFS-250 Home-Based Processor registration, $50/yr",
    "cap": "$60,000/yr",
    "products": "Non-perishable (breads, cookies, cakes, fruit/pecan pies)",
    "channels": "Direct in-state: pickup/delivery, markets, events, online",
    "label": "Name/address, net weight, allergens, processing date, &quot;home-produced and processed&quot; (10pt)",
    "inspectTrain": "Not required (HBP tier); not routinely inspected",
    "sources": "<a href=\"https://www.chfs.ky.gov/agencies/dph/dphps/fsb/Pages/homebasedprocessing.aspx\">KY CHFS</a>, <a href=\"https://forrager.com/law/kentucky/\">Forrager</a>",
    "details": "Permit: DFS-250 Home-Based Processor registration, $50/yr. Cap: $60,000/yr. Products: Non-perishable (breads, cookies, cakes, fruit/pecan pies). Channels: Direct in-state: pickup/delivery, markets, events, online. Label: Name/address, net weight, allergens, processing date, &quot;home-produced and processed&quot; (10pt). Inspect/Train: Not required (HBP tier); not routinely inspected. Sources: <a href=\"https://www.chfs.ky.gov/agencies/dph/dphps/fsb/Pages/homebasedprocessing.aspx\">KY CHFS</a>, <a href=\"https://forrager.com/law/kentucky/\">Forrager</a>"
  },
  {
    "state": "Louisiana",
    "permit": "No cottage-specific permit; needs state + parish sales tax certificates",
    "cap": "$30,000/yr",
    "products": "Notably allows <strong>pasteurized custard/cream fillings</strong> with temp controls (145°F/30min, chill ≤45°F)",
    "channels": "No resale to retail; direct sales implied",
    "label": "&quot;Not produced in a licensed or regulated facility.&quot;",
    "inspectTrain": "None found (temp-control rules substitute)",
    "sources": "<a href=\"https://law.justia.com/codes/louisiana/revised-statutes/title-40/rs-40-4-9/\">La. R.S. 40:4.9</a>, <a href=\"https://forrager.com/law/louisiana/\">Forrager</a>",
    "details": "Permit: No cottage-specific permit; needs state + parish sales tax certificates. Cap: $30,000/yr. Products: Notably allows <strong>pasteurized custard/cream fillings</strong> with temp controls (145°F/30min, chill ≤45°F). Channels: No resale to retail; direct sales implied. Label: &quot;Not produced in a licensed or regulated facility.&quot; Inspect/Train: None found (temp-control rules substitute). Sources: <a href=\"https://law.justia.com/codes/louisiana/revised-statutes/title-40/rs-40-4-9/\">La. R.S. 40:4.9</a>, <a href=\"https://forrager.com/law/louisiana/\">Forrager</a>"
  },
  {
    "state": "Maine",
    "permit": "Home Food Processor License, $20/yr, <strong>requires initial kitchen inspection</strong>",
    "cap": "None found",
    "products": "Non-perishable only",
    "channels": "Home sales (no label needed); retail store sales confirmed; restaurant/wholesale <strong>[UNCONFIRMED]</strong>",
    "label": "Required only for off-premises sales: product name, ingredients, net weight, producer name/address/zip",
    "inspectTrain": "Pre-licensing inspection required",
    "sources": "<a href=\"https://www.maine.gov/dacf/qar/permits_and_licenses/documents/home-license-101.pdf\">Maine DACF</a>, <a href=\"https://forrager.com/law/maine/\">Forrager</a>",
    "details": "Permit: Home Food Processor License, $20/yr, <strong>requires initial kitchen inspection</strong>. Cap: None found. Products: Non-perishable only. Channels: Home sales (no label needed); retail store sales confirmed; restaurant/wholesale <strong>[UNCONFIRMED]</strong>. Label: Required only for off-premises sales: product name, ingredients, net weight, producer name/address/zip. Inspect/Train: Pre-licensing inspection required. Sources: <a href=\"https://www.maine.gov/dacf/qar/permits_and_licenses/documents/home-license-101.pdf\">Maine DACF</a>, <a href=\"https://forrager.com/law/maine/\">Forrager</a>"
  },
  {
    "state": "Maryland",
    "permit": "None for direct sales; MDH approval required for retail store sales",
    "cap": "$50,000/yr",
    "products": "Non-perishable; high-acid fruit pies OK; no custard/cream/cheesecake/buttercream",
    "channels": "Direct in-state (markets, events, delivery, mail); retail only with MDH approval",
    "label": "Business name/ID, net weight, allergens, &quot;not subject to Maryland&#39;s food safety regulations.&quot;",
    "inspectTrain": "Only for retail-approved sellers (ANSI course, 3-yr validity)",
    "sources": "<a href=\"https://health.maryland.gov/phpa/OEHFP/OFPCHS/Documents/Updated_CF_Guidelines_2025.pdf\">MD DOH Guidelines 2025</a>, <a href=\"https://forrager.com/law/maryland/\">Forrager</a>",
    "details": "Permit: None for direct sales; MDH approval required for retail store sales. Cap: $50,000/yr. Products: Non-perishable; high-acid fruit pies OK; no custard/cream/cheesecake/buttercream. Channels: Direct in-state (markets, events, delivery, mail); retail only with MDH approval. Label: Business name/ID, net weight, allergens, &quot;not subject to Maryland&#39;s food safety regulations.&quot; Inspect/Train: Only for retail-approved sellers (ANSI course, 3-yr validity). Sources: <a href=\"https://health.maryland.gov/phpa/OEHFP/OFPCHS/Documents/Updated_CF_Guidelines_2025.pdf\">MD DOH Guidelines 2025</a>, <a href=\"https://forrager.com/law/maryland/\">Forrager</a>"
  },
  {
    "state": "Massachusetts",
    "permit": "Local Board of Health &quot;Retail Residential Kitchen&quot; permit; kitchen inspected before permit issued",
    "cap": "None found",
    "products": "Non-TCS only: no cream-filled pastries, cheesecake, custard",
    "channels": "Farmers markets, craft fairs, events, home, internet/mail direct; wholesale needs separate license",
    "label": "Operation name/address, ingredients (descending weight), allergens (all 9), nutrition labeling if claims made",
    "inspectTrain": "Local kitchen inspection + well testing; no statewide training requirement found",
    "sources": "<a href=\"https://www.mass.gov/info-details/residential-kitchen-questions-and-answers\">Mass.gov Residential Kitchen Q&amp;A</a>, <a href=\"https://forrager.com/law/massachusetts/\">Forrager</a>",
    "details": "Permit: Local Board of Health &quot;Retail Residential Kitchen&quot; permit; kitchen inspected before permit issued. Cap: None found. Products: Non-TCS only: no cream-filled pastries, cheesecake, custard. Channels: Farmers markets, craft fairs, events, home, internet/mail direct; wholesale needs separate license. Label: Operation name/address, ingredients (descending weight), allergens (all 9), nutrition labeling if claims made. Inspect/Train: Local kitchen inspection + well testing; no statewide training requirement found. Sources: <a href=\"https://www.mass.gov/info-details/residential-kitchen-questions-and-answers\">Mass.gov Residential Kitchen Q&amp;A</a>, <a href=\"https://forrager.com/law/massachusetts/\">Forrager</a>"
  },
  {
    "state": "Michigan",
    "permit": "None (exempt); optional MSU Product Center registration (~$50) to use a reg # instead of home address",
    "cap": "<strong>$50,000/yr standard; $75,000/yr if every product priced ≥$250/unit</strong> (new law eff. 3/24/2026, up from $25K)",
    "products": "Non-PHF; only two approved buttercream formulations; no cream cheese frosting/custards",
    "channels": "Home, markets, roadside stands, <strong>plus new (2026) online/mail order/3rd-party delivery: Michigan only</strong>",
    "label": "Name/address (or phone+reg#), net weight w/ metric, allergens, &quot;not been inspected by MDARD&quot; (≥11pt contrasting)",
    "inspectTrain": "None mandatory (MSU offers optional free course)",
    "sources": "<a href=\"https://www.michigan.gov/mdard/food-dairy/cottage-food\">MDARD</a>, <a href=\"https://www.farmtoconsumer.org/blog/2026/01/26/new-cottage-food-law-in-michigan/\">Farm-to-Consumer Legal Defense Fund</a>, <a href=\"https://forrager.com/law/michigan/\">Forrager</a>",
    "details": "Permit: None (exempt); optional MSU Product Center registration (~$50) to use a reg # instead of home address. Cap: <strong>$50,000/yr standard; $75,000/yr if every product priced ≥$250/unit</strong> (new law eff. 3/24/2026, up from $25K). Products: Non-PHF; only two approved buttercream formulations; no cream cheese frosting/custards. Channels: Home, markets, roadside stands, <strong>plus new (2026) online/mail order/3rd-party delivery: Michigan only</strong>. Label: Name/address (or phone+reg#), net weight w/ metric, allergens, &quot;not been inspected by MDARD&quot; (≥11pt contrasting). Inspect/Train: None mandatory (MSU offers optional free course). Sources: <a href=\"https://www.michigan.gov/mdard/food-dairy/cottage-food\">MDARD</a>, <a href=\"https://www.farmtoconsumer.org/blog/2026/01/26/new-cottage-food-law-in-michigan/\">Farm-to-Consumer Legal Defense Fund</a>, <a href=\"https://forrager.com/law/michigan/\">Forrager</a>"
  },
  {
    "state": "Minnesota",
    "permit": "Mandatory registration + training/exam. Tier 1 (≤$7,665): free. Tier 2 ($7,666–$78,000): $50, renewed every 3 yrs",
    "cap": "$78,000/yr (Tier 2 ceiling)",
    "products": "Non-PHF (water activity ≤0.85); no cream cheese frosting/fillings, custards, chocolate-covered items",
    "channels": "Home, markets, community events sold in person by registrant; online only if delivered in-person within MN",
    "label": "Reg # or address, production date, &quot;homemade and not subject to state inspection&quot; (label + website + point-of-sale)",
    "inspectTrain": "Tier 1 free training+exam; Tier 2 paid training every 3 yrs",
    "sources": "<a href=\"https://www.mda.state.mn.us/food-feed/cottage-food-law-guidance\">MDA Guidance</a>, <a href=\"https://forrager.com/law/minnesota/\">Forrager</a>",
    "details": "Permit: Mandatory registration + training/exam. Tier 1 (≤$7,665): free. Tier 2 ($7,666–$78,000): $50, renewed every 3 yrs. Cap: $78,000/yr (Tier 2 ceiling). Products: Non-PHF (water activity ≤0.85); no cream cheese frosting/fillings, custards, chocolate-covered items. Channels: Home, markets, community events sold in person by registrant; online only if delivered in-person within MN. Label: Reg # or address, production date, &quot;homemade and not subject to state inspection&quot; (label + website + point-of-sale). Inspect/Train: Tier 1 free training+exam; Tier 2 paid training every 3 yrs. Sources: <a href=\"https://www.mda.state.mn.us/food-feed/cottage-food-law-guidance\">MDA Guidance</a>, <a href=\"https://forrager.com/law/minnesota/\">Forrager</a>"
  },
  {
    "state": "Mississippi",
    "permit": "None (local zoning/business license may apply)",
    "cap": "$35,000/yr",
    "products": "No cream, custard, or dairy fillings",
    "channels": "Direct-to-consumer in person only: no shipping/wholesale/consignment/restaurant/grocery/out-of-state",
    "label": "Operation name/address, net weight, allergens, &quot;not subject to Mississippi&#39;s food safety regulations&quot; (≥10pt)",
    "inspectTrain": "Only on complaint; training &quot;encouraged,&quot; not required",
    "sources": "<a href=\"https://msdh.ms.gov/page/resources/5375.pdf\">MSDH FAQ</a>, <a href=\"https://forrager.com/law/mississippi/\">Forrager</a>",
    "details": "Permit: None (local zoning/business license may apply). Cap: $35,000/yr. Products: No cream, custard, or dairy fillings. Channels: Direct-to-consumer in person only: no shipping/wholesale/consignment/restaurant/grocery/out-of-state. Label: Operation name/address, net weight, allergens, &quot;not subject to Mississippi&#39;s food safety regulations&quot; (≥10pt). Inspect/Train: Only on complaint; training &quot;encouraged,&quot; not required. Sources: <a href=\"https://msdh.ms.gov/page/resources/5375.pdf\">MSDH FAQ</a>, <a href=\"https://forrager.com/law/mississippi/\">Forrager</a>"
  },
  {
    "state": "Missouri",
    "permit": "None",
    "cap": "None (former $50K cap removed 8/28/2022)",
    "products": "Non-PHF; excludes cream/meringue pies, fresh-fruit-garnished goods, dairy fillings",
    "channels": "Direct-to-consumer only (in-state online OK); no wholesale/out-of-state/farmers-market-or-retail under this specific law (separate county-opt-in &quot;food stand&quot; law exists)",
    "label": "Common food name, net weight, allergens, &quot;not inspected by the health department.&quot;",
    "inspectTrain": "None",
    "sources": "<a href=\"https://health.mo.gov/safety/foodsafety/pdf/home-based-kitchen-food-prod-guidance.pdf\">MO DHSS Guidance</a>, <a href=\"https://forrager.com/law/missouri/\">Forrager</a>",
    "details": "Permit: None. Cap: None (former $50K cap removed 8/28/2022). Products: Non-PHF; excludes cream/meringue pies, fresh-fruit-garnished goods, dairy fillings. Channels: Direct-to-consumer only (in-state online OK); no wholesale/out-of-state/farmers-market-or-retail under this specific law (separate county-opt-in &quot;food stand&quot; law exists). Label: Common food name, net weight, allergens, &quot;not inspected by the health department.&quot; Inspect/Train: None. Sources: <a href=\"https://health.mo.gov/safety/foodsafety/pdf/home-based-kitchen-food-prod-guidance.pdf\">MO DHSS Guidance</a>, <a href=\"https://forrager.com/law/missouri/\">Forrager</a>"
  },
  {
    "state": "Montana",
    "permit": "None (Local Food Choice Act exempts from licensing/permitting/inspection)",
    "cap": "None stated",
    "products": "Homemade baked goods generally allowed; dairy-based frostings/fillings <strong>[UNCONFIRMED/ambiguous: recommend direct confirmation with MT DPHHS]</strong>",
    "channels": "Direct in-person only: home, farm/ranch, &quot;traditional community social event&quot;; no third parties/roadside stands/vehicles",
    "label": "No fixed format: must verbally/in writing inform customer food is unlicensed/uninspected",
    "inspectTrain": "None permitted by statute",
    "sources": "<a href=\"https://www.dphhs.mt.gov/assets/publichealth/FCS/CottageFood/MTLocalFoodChoiceActGuidanceDoc_.pdf\">MT DPHHS Guidance</a>, <a href=\"https://forrager.com/law/montana/\">Forrager</a>",
    "details": "Permit: None (Local Food Choice Act exempts from licensing/permitting/inspection). Cap: None stated. Products: Homemade baked goods generally allowed; dairy-based frostings/fillings <strong>[UNCONFIRMED/ambiguous: recommend direct confirmation with MT DPHHS]</strong>. Channels: Direct in-person only: home, farm/ranch, &quot;traditional community social event&quot;; no third parties/roadside stands/vehicles. Label: No fixed format: must verbally/in writing inform customer food is unlicensed/uninspected. Inspect/Train: None permitted by statute. Sources: <a href=\"https://www.dphhs.mt.gov/assets/publichealth/FCS/CottageFood/MTLocalFoodChoiceActGuidanceDoc_.pdf\">MT DPHHS Guidance</a>, <a href=\"https://forrager.com/law/montana/\">Forrager</a>"
  },
  {
    "state": "Nebraska",
    "permit": "Free registration with NE Dept. of Agriculture (contact info + training completion + well-test date if applicable)",
    "cap": "None",
    "products": "<strong>Notably broader</strong>: allows some TCS items with commercially-produced dairy (cheesecake, whipped cream, pudding) if hand-delivered within 2 hrs and refrigerated",
    "channels": "Direct-to-consumer only: markets, fairs, events, home pickup/delivery; no restaurants/retail/wholesale/out-of-state",
    "label": "Producer name/address, allergen warning, &quot;prepared in a kitchen not subject to regulation and inspection...may contain allergens&quot; (label, website, ads)",
    "inspectTrain": "No inspection; accredited training (ServSafe/UNL) required before registering",
    "sources": "<a href=\"https://nda.nebraska.gov/fscp/foods/cottagefood\">NE Dept. of Ag</a>, <a href=\"https://forrager.com/law/nebraska/\">Forrager</a>",
    "details": "Permit: Free registration with NE Dept. of Agriculture (contact info + training completion + well-test date if applicable). Cap: None. Products: <strong>Notably broader</strong>: allows some TCS items with commercially-produced dairy (cheesecake, whipped cream, pudding) if hand-delivered within 2 hrs and refrigerated. Channels: Direct-to-consumer only: markets, fairs, events, home pickup/delivery; no restaurants/retail/wholesale/out-of-state. Label: Producer name/address, allergen warning, &quot;prepared in a kitchen not subject to regulation and inspection...may contain allergens&quot; (label, website, ads). Inspect/Train: No inspection; accredited training (ServSafe/UNL) required before registering. Sources: <a href=\"https://nda.nebraska.gov/fscp/foods/cottagefood\">NE Dept. of Ag</a>, <a href=\"https://forrager.com/law/nebraska/\">Forrager</a>"
  },
  {
    "state": "Nevada",
    "permit": "Register with local health district (not state); county fees vary (Clark County $200+)",
    "cap": "$35,000/yr <strong>[note: Forrager lists $100,000: conflicts with two official sources at $35K; verify directly with NV DPBH before publishing]</strong>",
    "products": "Shelf-stable only: no cream frosting/ganache, cream cheese, custards, soft cheeses",
    "channels": "Direct in-person only (home, markets, swap meets, church bazaars, fairs); orders may be placed online/phone but goods can&#39;t be mailed/3rd-party delivered",
    "label": "&quot;MADE IN A COTTAGE FOOD OPERATION THAT IS NOT SUBJECT TO GOVERNMENT FOOD SAFETY INSPECTION,&quot; min 1/16&quot; print",
    "inspectTrain": "None except complaint-driven; oversight shifts to state Dept. of Ag July 2027",
    "sources": "<a href=\"https://www.dpbh.nv.gov/siteassets/regulatory/environmental-health/cottage-food/bakinginnevada.pdf\">NV DPBH</a>, <a href=\"https://www.southernnevadahealthdistrict.org/permits-and-regulations/cottage-food-operations/cottage-food-faq/\">SNHD FAQ</a>, <a href=\"https://forrager.com/law/nevada/\">Forrager</a>",
    "details": "Permit: Register with local health district (not state); county fees vary (Clark County $200+). Cap: $35,000/yr <strong>[note: Forrager lists $100,000: conflicts with two official sources at $35K; verify directly with NV DPBH before publishing]</strong>. Products: Shelf-stable only: no cream frosting/ganache, cream cheese, custards, soft cheeses. Channels: Direct in-person only (home, markets, swap meets, church bazaars, fairs); orders may be placed online/phone but goods can&#39;t be mailed/3rd-party delivered. Label: &quot;MADE IN A COTTAGE FOOD OPERATION THAT IS NOT SUBJECT TO GOVERNMENT FOOD SAFETY INSPECTION,&quot; min 1/16&quot; print. Inspect/Train: None except complaint-driven; oversight shifts to state Dept. of Ag July 2027. Sources: <a href=\"https://www.dpbh.nv.gov/siteassets/regulatory/environmental-health/cottage-food/bakinginnevada.pdf\">NV DPBH</a>, <a href=\"https://www.southernnevadahealthdistrict.org/permits-and-regulations/cottage-food-operations/cottage-food-faq/\">SNHD FAQ</a>, <a href=\"https://forrager.com/law/nevada/\">Forrager</a>"
  },
  {
    "state": "New Hampshire",
    "permit": "Two tiers: <strong>Unlicensed</strong> (free, non-hazardous, sold direct from residence/farmstand/market/retail store per NH DHHS); <strong>Licensed &quot;Homestead Food Operation&quot; (Class H)</strong> $150/yr for online/mail/wholesale/most restaurant sales",
    "cap": "None either tier",
    "products": "Breads, cookies, double-crust fruit pies, candy/fudge; no cheesecake, pumpkin pie, custards, cream cheese frosting",
    "channels": "Unlicensed: residence, farmstand, market, retail store (verify this retail claim directly, it&#39;s an outlier vs. other states); Licensed adds online/mail/wholesale/restaurants",
    "label": "Licensed adds &quot;licensed by NH DHHS&quot;; Unlicensed adds &quot;exempt from NH licensing and inspection&quot; (≥10pt)",
    "inspectTrain": "Licensed tier has facility standards + well testing; no formal course requirement found",
    "sources": "<a href=\"https://www.dhhs.nh.gov/programs-services/environmental-health-and-you/food-protection/homestead-food-operations\">NH DHHS</a>, <a href=\"https://forrager.com/law/new-hampshire/\">Forrager</a>",
    "details": "Permit: Two tiers: <strong>Unlicensed</strong> (free, non-hazardous, sold direct from residence/farmstand/market/retail store per NH DHHS); <strong>Licensed &quot;Homestead Food Operation&quot; (Class H)</strong> $150/yr for online/mail/wholesale/most restaurant sales. Cap: None either tier. Products: Breads, cookies, double-crust fruit pies, candy/fudge; no cheesecake, pumpkin pie, custards, cream cheese frosting. Channels: Unlicensed: residence, farmstand, market, retail store (verify this retail claim directly, it&#39;s an outlier vs. other states); Licensed adds online/mail/wholesale/restaurants. Label: Licensed adds &quot;licensed by NH DHHS&quot;; Unlicensed adds &quot;exempt from NH licensing and inspection&quot; (≥10pt). Inspect/Train: Licensed tier has facility standards + well testing; no formal course requirement found. Sources: <a href=\"https://www.dhhs.nh.gov/programs-services/environmental-health-and-you/food-protection/homestead-food-operations\">NH DHHS</a>, <a href=\"https://forrager.com/law/new-hampshire/\">Forrager</a>"
  },
  {
    "state": "New Jersey",
    "permit": "Cottage Food Operator&#39;s Permit required, $100 fee; needs local zoning approval, <strong>Food Protection Manager certification</strong>, and proof of safe kitchen water",
    "cap": "$50,000/yr",
    "products": "Breads, cakes, cookies, brownies, muffins, macarons, donuts, etc.: cheese/cream-filled pastries excluded",
    "channels": "Direct-to-consumer only (operator&#39;s home, consumer&#39;s home in-NJ, markets, farm stands, temporary retail events): no shipping/mail/wholesale/retail-store",
    "label": "Permit #, municipality + &quot;NJ,&quot; &quot;prepared...in a home kitchen that has not been inspected by the Department of Health.&quot;",
    "inspectTrain": "Not inspected except complaint; Food Protection Manager cert required pre-permit",
    "sources": "<a href=\"https://www.nj.gov/health/cottagefood/\">NJ DOH</a>, <a href=\"https://forrager.com/law/new-jersey/\">Forrager</a>",
    "details": "<strong>Correction to common assumption: NJ is no longer a &quot;no cottage food law&quot; state.</strong> It adopted its first law (N.J.A.C. 8:24-11) effective October 4, 2021. Permit: Cottage Food Operator&#39;s Permit required, $100 fee; needs local zoning approval, <strong>Food Protection Manager certification</strong>, and proof of safe kitchen water. Cap: $50,000/yr. Products: Breads, cakes, cookies, brownies, muffins, macarons, donuts, etc.: cheese/cream-filled pastries excluded. Channels: Direct-to-consumer only (operator&#39;s home, consumer&#39;s home in-NJ, markets, farm stands, temporary retail events): no shipping/mail/wholesale/retail-store. Label: Permit #, municipality + &quot;NJ,&quot; &quot;prepared...in a home kitchen that has not been inspected by the Department of Health.&quot; Inspect/Train: Not inspected except complaint; Food Protection Manager cert required pre-permit. Sources: <a href=\"https://www.nj.gov/health/cottagefood/\">NJ DOH</a>, <a href=\"https://forrager.com/law/new-jersey/\">Forrager</a>"
  },
  {
    "state": "New Mexico",
    "permit": "<strong>[UNCONFIRMED sales cap: could not verify from primary source]</strong>; generally light registration model. Products/Channels/",
    "cap": "",
    "products": "",
    "channels": "",
    "label": "Broadly similar to other no-inspection light-touch states. Recommend direct confirmation with NM Environment Department before publishing details",
    "inspectTrain": "",
    "sources": "<a href=\"https://forrager.com/law/new-mexico/\">Forrager</a>",
    "details": "Permit: <strong>[UNCONFIRMED sales cap: could not verify from primary source]</strong>; generally light registration model. Products/Channels/Label: Broadly similar to other no-inspection light-touch states. Recommend direct confirmation with NM Environment Department before publishing details. Sources: <a href=\"https://forrager.com/law/new-mexico/\">Forrager</a>"
  },
  {
    "state": "New York",
    "permit": "<strong>Single free registration tier, no sales cap</strong>: I could not confirm a &quot;two-tier exemption vs. license&quot; structure that&#39;s sometimes assumed; current sources point to one registration path",
    "cap": "",
    "products": "Non-PHF baked goods",
    "channels": "Direct sales, markets, in-state online",
    "label": "Standard elements + home-processor disclosure",
    "inspectTrain": "No inspection for registration tier. Note: if you&#39;ve seen a two-tier claim elsewhere, it&#39;s worth sourcing directly: current official guidance didn&#39;t corroborate it",
    "sources": "<a href=\"https://forrager.com/law/new-york/\">Forrager</a>, NY Dept. of Ag &amp; Markets",
    "details": "Permit: <strong>Single free registration tier, no sales cap</strong>: I could not confirm a &quot;two-tier exemption vs. license&quot; structure that&#39;s sometimes assumed; current sources point to one registration path. Products: Non-PHF baked goods. Channels: Direct sales, markets, in-state online. Label: Standard elements + home-processor disclosure. Inspect/Train: No inspection for registration tier. Note: if you&#39;ve seen a two-tier claim elsewhere, it&#39;s worth sourcing directly: current official guidance didn&#39;t corroborate it. Sources: <a href=\"https://forrager.com/law/new-york/\">Forrager</a>, NY Dept. of Ag &amp; Markets"
  },
  {
    "state": "North Carolina",
    "permit": "<strong>Requires an actual home kitchen inspection</strong> (free): not a light-touch state",
    "cap": "",
    "products": "Non-perishable baked goods",
    "channels": "Direct sales, markets, in-state online",
    "label": "Standard elements + home-processor disclosure",
    "inspectTrain": "Home kitchen inspection required",
    "sources": "<a href=\"https://forrager.com/law/north-carolina/\">Forrager</a>, NC Dept. of Agriculture &amp; Consumer Services",
    "details": "Permit: <strong>Requires an actual home kitchen inspection</strong> (free): not a light-touch state. Products: Non-perishable baked goods. Channels: Direct sales, markets, in-state online. Label: Standard elements + home-processor disclosure. Inspect/Train: Home kitchen inspection required. Sources: <a href=\"https://forrager.com/law/north-carolina/\">Forrager</a>, NC Dept. of Agriculture &amp; Consumer Services"
  },
  {
    "state": "North Dakota",
    "permit": "Light-touch, no inspection model (similar to SD/ND food-freedom-adjacent states)",
    "cap": "",
    "products": "Non-perishable",
    "channels": "Direct sales, markets",
    "label": "Standard elements",
    "inspectTrain": "None",
    "sources": "<a href=\"https://forrager.com/law/north-dakota/\">Forrager</a>",
    "details": "Permit: Light-touch, no inspection model (similar to SD/ND food-freedom-adjacent states). Products: Non-perishable. Channels: Direct sales, markets. Label: Standard elements. Inspect/Train: None. Sources: <a href=\"https://forrager.com/law/north-dakota/\">Forrager</a>"
  },
  {
    "state": "Ohio",
    "permit": "Registration/licensing varies by product risk tier; standard non-perishable baked goods generally lighter touch",
    "cap": "",
    "products": "Non-perishable baked goods",
    "channels": "Direct sales, markets, in-state online",
    "label": "Standard elements + disclosure",
    "inspectTrain": "Varies by tier",
    "sources": "<a href=\"https://forrager.com/law/ohio/\">Forrager</a>, Ohio Dept. of Agriculture",
    "details": "Permit: Registration/licensing varies by product risk tier; standard non-perishable baked goods generally lighter touch. Products: Non-perishable baked goods. Channels: Direct sales, markets, in-state online. Label: Standard elements + disclosure. Inspect/Train: Varies by tier. Sources: <a href=\"https://forrager.com/law/ohio/\">Forrager</a>, Ohio Dept. of Agriculture"
  },
  {
    "state": "Oklahoma",
    "permit": "Registration model",
    "cap": "<strong>$75,000/yr today: rising to $250,000/yr on November 1, 2026</strong> under a recently signed law",
    "products": "Non-perishable baked goods",
    "channels": "Direct sales, markets, in-state online",
    "label": "Standard elements + disclosure",
    "inspectTrain": "Varies",
    "sources": "<a href=\"https://forrager.com/law/oklahoma/\">Forrager</a>, Oklahoma Dept. of Agriculture, Food &amp; Forestry",
    "details": "Permit: Registration model. Cap: <strong>$75,000/yr today: rising to $250,000/yr on November 1, 2026</strong> under a recently signed law. Products: Non-perishable baked goods. Channels: Direct sales, markets, in-state online. Label: Standard elements + disclosure. Inspect/Train: Varies. Sources: <a href=\"https://forrager.com/law/oklahoma/\">Forrager</a>, Oklahoma Dept. of Agriculture, Food &amp; Forestry"
  },
  {
    "state": "Oregon",
    "permit": "Registration/exemption model, generally light-touch for baked goods",
    "cap": "",
    "products": "Non-perishable baked goods",
    "channels": "Direct sales, markets, in-state online",
    "label": "Standard elements + disclosure",
    "inspectTrain": "Generally none for basic tier",
    "sources": "<a href=\"https://forrager.com/law/oregon/\">Forrager</a>, Oregon Dept. of Agriculture",
    "details": "Permit: Registration/exemption model, generally light-touch for baked goods. Products: Non-perishable baked goods. Channels: Direct sales, markets, in-state online. Label: Standard elements + disclosure. Inspect/Train: Generally none for basic tier. Sources: <a href=\"https://forrager.com/law/oregon/\">Forrager</a>, Oregon Dept. of Agriculture"
  },
  {
    "state": "Pennsylvania",
    "permit": "<strong>Requires home kitchen inspection, $35/yr</strong>: not a light-touch state",
    "cap": "",
    "products": "Non-perishable baked goods",
    "channels": "Direct sales, markets, in-state online",
    "label": "Standard elements + disclosure wording <strong>[UNCONFIRMED exact text]</strong>",
    "inspectTrain": "Home kitchen inspection required",
    "sources": "<a href=\"https://forrager.com/law/pennsylvania/\">Forrager</a>, PA Dept. of Agriculture",
    "details": "Permit: <strong>Requires home kitchen inspection, $35/yr</strong>: not a light-touch state. Products: Non-perishable baked goods. Channels: Direct sales, markets, in-state online. Label: Standard elements + disclosure wording <strong>[UNCONFIRMED exact text]</strong>. Inspect/Train: Home kitchen inspection required. Sources: <a href=\"https://forrager.com/law/pennsylvania/\">Forrager</a>, PA Dept. of Agriculture"
  },
  {
    "state": "Rhode Island",
    "permit": "Registration model",
    "cap": "",
    "products": "Non-perishable baked goods: doughnut/tortilla exclusion noted by some sources <strong>[UNCONFIRMED]</strong>",
    "channels": "Direct sales, markets",
    "label": "Standard elements",
    "inspectTrain": "Varies",
    "sources": "<a href=\"https://forrager.com/law/rhode-island/\">Forrager</a>, RI Dept. of Health",
    "details": "Permit: Registration model. Products: Non-perishable baked goods: doughnut/tortilla exclusion noted by some sources <strong>[UNCONFIRMED]</strong>. Channels: Direct sales, markets. Label: Standard elements. Inspect/Train: Varies. Sources: <a href=\"https://forrager.com/law/rhode-island/\">Forrager</a>, RI Dept. of Health"
  },
  {
    "state": "South Carolina",
    "permit": "Light-touch registration/exemption model",
    "cap": "",
    "products": "Non-perishable baked goods",
    "channels": "Direct sales, markets, in-state online",
    "label": "Standard elements + disclosure",
    "inspectTrain": "Generally none for basic tier",
    "sources": "<a href=\"https://forrager.com/law/south-carolina/\">Forrager</a>, SC Dept. of Agriculture",
    "details": "Permit: Light-touch registration/exemption model. Products: Non-perishable baked goods. Channels: Direct sales, markets, in-state online. Label: Standard elements + disclosure. Inspect/Train: Generally none for basic tier. Sources: <a href=\"https://forrager.com/law/south-carolina/\">Forrager</a>, SC Dept. of Agriculture"
  },
  {
    "state": "South Dakota",
    "permit": "None for non-perishable; paid training (~$40, valid 5 yrs) required for perishable/temp-controlled items",
    "cap": "None stated",
    "products": "Non-perishable (cookies, rolls, cakes, breads, lefse, hard candies); perishable allowed only if ≤41°F + training",
    "channels": "Home, markets, roadside stands, temp venues, direct delivery; no shipping. A 2025 bill (HB 1179) referencing 3rd-party retail sale is <strong>[UNCONFIRMED: unclear if signed into law]</strong>",
    "label": "Producer contact, production date, allergen disclaimer, refrigeration instructions",
    "inspectTrain": "Only for perishable tier",
    "sources": "<a href=\"https://doh.sd.gov/topics/food-lodging-safety/farmers-markets/\">SD DOH</a>, <a href=\"https://extension.sdstate.edu/south-dakota-cottage-home-processing-food-safety\">SDSU Extension</a>, <a href=\"https://forrager.com/law/south-dakota/\">Forrager</a>",
    "details": "Permit: None for non-perishable; paid training (~$40, valid 5 yrs) required for perishable/temp-controlled items. Cap: None stated. Products: Non-perishable (cookies, rolls, cakes, breads, lefse, hard candies); perishable allowed only if ≤41°F + training. Channels: Home, markets, roadside stands, temp venues, direct delivery; no shipping. A 2025 bill (HB 1179) referencing 3rd-party retail sale is <strong>[UNCONFIRMED: unclear if signed into law]</strong>. Label: Producer contact, production date, allergen disclaimer, refrigeration instructions. Inspect/Train: Only for perishable tier. Sources: <a href=\"https://doh.sd.gov/topics/food-lodging-safety/farmers-markets/\">SD DOH</a>, <a href=\"https://extension.sdstate.edu/south-dakota-cottage-home-processing-food-safety\">SDSU Extension</a>, <a href=\"https://forrager.com/law/south-dakota/\">Forrager</a>"
  },
  {
    "state": "Tennessee",
    "permit": "None: Food Freedom Act (amended eff. 7/1/2025) exempts from licensing/permitting/inspection",
    "cap": "None",
    "products": "Broad range including perishable baked goods; no alcohol-containing items",
    "channels": "Perishable = in-person only; non-perishable = markets, home, retail, roadside stands; not restaurants",
    "label": "Business name/address/phone, homemade/allergen statement",
    "inspectTrain": "None",
    "sources": "<a href=\"https://www.tn.gov/agriculture/consumers/food-safety/tennessee-food-freedom-act.html\">TN Ag Dept.</a>, <a href=\"https://forrager.com/law/tennessee/\">Forrager</a>",
    "details": "Permit: None: Food Freedom Act (amended eff. 7/1/2025) exempts from licensing/permitting/inspection. Cap: None. Products: Broad range including perishable baked goods; no alcohol-containing items. Channels: Perishable = in-person only; non-perishable = markets, home, retail, roadside stands; not restaurants. Label: Business name/address/phone, homemade/allergen statement. Inspect/Train: None. Sources: <a href=\"https://www.tn.gov/agriculture/consumers/food-safety/tennessee-food-freedom-act.html\">TN Ag Dept.</a>, <a href=\"https://forrager.com/law/tennessee/\">Forrager</a>"
  },
  {
    "state": "Texas",
    "permit": "Free DSHS registration only if selling perishable/TCS items (e.g. cheesecake); none for standard goods",
    "cap": "$150,000/yr (inflation-adjusted)",
    "products": "Non-perishable freely; perishable/TCS (custard, cream-cheese frosting) allowed with registration; no meat/seafood/low-acid canned",
    "channels": "<strong>Broadest of any state researched</strong>: direct, markets, online, and retail stores/restaurants for non-perishable",
    "label": "&quot;PRODUCED IN A PRIVATE RESIDENCE...&quot; disclaimer, ID#, allergens; TCS items add date + handling instructions",
    "inspectTrain": "Food handler cert required",
    "sources": "<a href=\"https://www.dshs.texas.gov/retail-food-establishments/permits-retail-food-establishments/texas-cottage-food-production\">TX DSHS</a>, <a href=\"https://forrager.com/law/texas/\">Forrager</a>",
    "details": "Permit: Free DSHS registration only if selling perishable/TCS items (e.g. cheesecake); none for standard goods. Cap: $150,000/yr (inflation-adjusted). Products: Non-perishable freely; perishable/TCS (custard, cream-cheese frosting) allowed with registration; no meat/seafood/low-acid canned. Channels: <strong>Broadest of any state researched</strong>: direct, markets, online, and retail stores/restaurants for non-perishable. Label: &quot;PRODUCED IN A PRIVATE RESIDENCE...&quot; disclaimer, ID#, allergens; TCS items add date + handling instructions. Inspect/Train: Food handler cert required. Sources: <a href=\"https://www.dshs.texas.gov/retail-food-establishments/permits-retail-food-establishments/texas-cottage-food-production\">TX DSHS</a>, <a href=\"https://forrager.com/law/texas/\">Forrager</a>"
  },
  {
    "state": "Utah",
    "permit": "",
    "cap": "",
    "products": "",
    "channels": "",
    "label": "Cottage Food Act: &quot;Home Produced&quot; + standard elements; Food Freedom Act: business name/address, allergens, &quot;not for resale...without state or local inspection.&quot;",
    "inspectTrain": "",
    "sources": "<a href=\"https://ag.utah.gov/regulatory-services/cottage-food-production/\">Utah Ag Dept.</a>, <a href=\"https://forrager.com/law/utah/\">Forrager</a>",
    "details": "<strong>Two parallel laws.</strong> (1) Cottage Food Act: food handler permit + UDAF registration/inspection, shelf-stable only, direct or retail resale in-state. (2) Food Freedom Act (HB 181, 2018): no licensing/permitting/inspection at all, unlimited sales, allows cream/custard-filled and alcohol-containing baked goods, but limited to home/agreed locations/farmers-market homemade-food sections (no restaurants/retail/festivals). Label: Cottage Food Act: &quot;Home Produced&quot; + standard elements; Food Freedom Act: business name/address, allergens, &quot;not for resale...without state or local inspection.&quot; Sources: <a href=\"https://ag.utah.gov/regulatory-services/cottage-food-production/\">Utah Ag Dept.</a>, <a href=\"https://forrager.com/law/utah/\">Forrager</a>"
  },
  {
    "state": "Vermont",
    "permit": "",
    "cap": "",
    "products": "Non-perishable only",
    "channels": "Direct only: markets, events, home, online, roadside stands; no restaurants/retail",
    "label": "Standard elements",
    "inspectTrain": "Pre-2025 none; Act 42 adds a training/attestation requirement with unclear details. Recommend a direct call to VT before publishing anything state-specific",
    "sources": "<a href=\"https://legislature.vermont.gov/statutes/section/18/085/04301\">VT Statutes §4301</a>, <a href=\"https://legislature.vermont.gov/Documents/2026/Docs/ACTS/ACT042/ACT042%20As%20Enacted.pdf\">Act 42 (2025)</a>, <a href=\"https://forrager.com/law/vermont/\">Forrager</a>",
    "details": "<strong>Messiest entry: flagged for follow-up.</strong> Changed by 2025 Act 42 (eff. 7/1/2025): exempt if ≤$125/week (home bakery) or ≤$30,000/yr (general cottage food); above that, older guidance describes a $100/yr license + annual inspection that <strong>may be superseded</strong> by Act 42: exact interaction <strong>[UNCONFIRMED]</strong>. Products: Non-perishable only. Channels: Direct only: markets, events, home, online, roadside stands; no restaurants/retail. Label: Standard elements. Inspect/Train: Pre-2025 none; Act 42 adds a training/attestation requirement with unclear details. Recommend a direct call to VT before publishing anything state-specific. Sources: <a href=\"https://legislature.vermont.gov/statutes/section/18/085/04301\">VT Statutes §4301</a>, <a href=\"https://legislature.vermont.gov/Documents/2026/Docs/ACTS/ACT042/ACT042%20As%20Enacted.pdf\">Act 42 (2025)</a>, <a href=\"https://forrager.com/law/vermont/\">Forrager</a>"
  },
  {
    "state": "Virginia",
    "permit": "None from VDACS (self-administered); local business license/zoning may apply",
    "cap": "None for baked goods ($9,000/yr cap applies only to acidified foods)",
    "products": "Non-hazardous only: no meat/cheese/cream fillings",
    "channels": "Home, markets, temp events (≤14 days): no retail/restaurants/wholesale/online sale-payment/shipping/out-of-state",
    "label": "&quot;NOT FOR RESALE: PROCESSED AND PREPARED WITHOUT STATE INSPECTION.&quot;",
    "inspectTrain": "None",
    "sources": "<a href=\"https://www.vdacs.virginia.gov/pdf/kitchenbillfaq.pdf\">VDACS FAQ</a>, <a href=\"https://forrager.com/law/virginia/\">Forrager</a>",
    "details": "Permit: None from VDACS (self-administered); local business license/zoning may apply. Cap: None for baked goods ($9,000/yr cap applies only to acidified foods). Products: Non-hazardous only: no meat/cheese/cream fillings. Channels: Home, markets, temp events (≤14 days): no retail/restaurants/wholesale/online sale-payment/shipping/out-of-state. Label: &quot;NOT FOR RESALE: PROCESSED AND PREPARED WITHOUT STATE INSPECTION.&quot; Inspect/Train: None. Sources: <a href=\"https://www.vdacs.virginia.gov/pdf/kitchenbillfaq.pdf\">VDACS FAQ</a>, <a href=\"https://forrager.com/law/virginia/\">Forrager</a>"
  },
  {
    "state": "Washington",
    "permit": "<strong>Cottage Food Permit required</strong>: $355/2-yr + Food Worker Card (~$10) + business license; floor plan/labels/inspection docs required",
    "cap": "$35,000/yr (inflation-adjusted every 4 yrs)",
    "products": "Non-PHF; pies excluding custard/unbaked fruit/refrigerated; shelf-stable frostings only",
    "channels": "Direct-to-consumer only: markets, home, events, craft fairs; no shipping/3rd-party delivery/mail/restaurants/retail",
    "label": "Permit #, allergens, net weight, &quot;MADE IN A HOME KITCHEN THAT HAS NOT BEEN SUBJECT TO STANDARD INSPECTION CRITERIA.&quot;",
    "inspectTrain": "Food Worker Card + mandatory home kitchen inspection (initial + annual)",
    "sources": "<a href=\"https://agr.wa.gov/cottagefood\">WSDA</a>, <a href=\"https://forrager.com/law/washington/\">Forrager</a>",
    "details": "Permit: <strong>Cottage Food Permit required</strong>: $355/2-yr + Food Worker Card (~$10) + business license; floor plan/labels/inspection docs required. Cap: $35,000/yr (inflation-adjusted every 4 yrs). Products: Non-PHF; pies excluding custard/unbaked fruit/refrigerated; shelf-stable frostings only. Channels: Direct-to-consumer only: markets, home, events, craft fairs; no shipping/3rd-party delivery/mail/restaurants/retail. Label: Permit #, allergens, net weight, &quot;MADE IN A HOME KITCHEN THAT HAS NOT BEEN SUBJECT TO STANDARD INSPECTION CRITERIA.&quot; Inspect/Train: Food Worker Card + mandatory home kitchen inspection (initial + annual). Sources: <a href=\"https://agr.wa.gov/cottagefood\">WSDA</a>, <a href=\"https://forrager.com/law/washington/\">Forrager</a>"
  },
  {
    "state": "West Virginia",
    "permit": "None: Food Freedom-style (SB 285, 2019). Separate ~$35/yr WVDA farmers-market permit applies only to potentially-hazardous items (not plain baked goods)",
    "cap": "Unlimited",
    "products": "Shelf-stable only: no cream/custard/cheese/meat fillings",
    "channels": "Home, markets, community events, online orders w/ mail or in-person delivery",
    "label": "Producer name/address/phone, &quot;produced at a private residence exempt from State licensing and inspection...may contain allergens.&quot;",
    "inspectTrain": "None",
    "sources": "<a href=\"https://www.wvlegislature.gov/Bill_Text_HTML/2019_SESSIONS/RS/bills/SB285%20SUB2%20ENR.pdf\">SB 285</a>, <a href=\"https://forrager.com/law/west-virginia/\">Forrager</a>",
    "details": "Permit: None: Food Freedom-style (SB 285, 2019). Separate ~$35/yr WVDA farmers-market permit applies only to potentially-hazardous items (not plain baked goods). Cap: Unlimited. Products: Shelf-stable only: no cream/custard/cheese/meat fillings. Channels: Home, markets, community events, online orders w/ mail or in-person delivery. Label: Producer name/address/phone, &quot;produced at a private residence exempt from State licensing and inspection...may contain allergens.&quot; Inspect/Train: None. Sources: <a href=\"https://www.wvlegislature.gov/Bill_Text_HTML/2019_SESSIONS/RS/bills/SB285%20SUB2%20ENR.pdf\">SB 285</a>, <a href=\"https://forrager.com/law/west-virginia/\">Forrager</a>"
  },
  {
    "state": "Wisconsin",
    "permit": "<strong>No statute: court-created exemption only</strong> (2017 ruling, upheld on appeal; never codified by the legislature). No license for qualifying baked goods",
    "cap": "Unlimited for baked goods",
    "products": "Shelf-stable, oven dry-heat &gt;140°F only (dehydrated items don&#39;t qualify); custard/cream/cheesecake fillings and unbaked dough remain illegal without a license",
    "channels": "Direct-to-consumer + in-state mail order; no interstate shipping/restaurants/retail/wholesale without a license",
    "label": "No statutory requirement (no statute exists) but disclaimer/ingredients/allergens/net weight/producer info strongly recommended",
    "inspectTrain": "None required",
    "sources": "<a href=\"https://datcp.wi.gov/Pages/Licenses_Permits/HomeBakers.aspx\">WI DATCP</a>, <a href=\"https://forrager.com/law/wisconsin/\">Forrager</a>",
    "details": "Permit: <strong>No statute: court-created exemption only</strong> (2017 ruling, upheld on appeal; never codified by the legislature). No license for qualifying baked goods. Cap: Unlimited for baked goods. Products: Shelf-stable, oven dry-heat &gt;140°F only (dehydrated items don&#39;t qualify); custard/cream/cheesecake fillings and unbaked dough remain illegal without a license. Channels: Direct-to-consumer + in-state mail order; no interstate shipping/restaurants/retail/wholesale without a license. Label: No statutory requirement (no statute exists) but disclaimer/ingredients/allergens/net weight/producer info strongly recommended. Inspect/Train: None required. Sources: <a href=\"https://datcp.wi.gov/Pages/Licenses_Permits/HomeBakers.aspx\">WI DATCP</a>, <a href=\"https://forrager.com/law/wisconsin/\">Forrager</a>"
  },
  {
    "state": "Wyoming",
    "permit": "None: Food Freedom Act (W.S. §11-49); no license, inspection, or training needed",
    "cap": "Reported as $250,000/yr by secondary sources <strong>[UNCONFIRMED against statute text directly]</strong>",
    "products": "Non-perishable sellable anywhere incl. retail/wholesale; perishable (dairy fillings, wedding cakes) direct-to-consumer only",
    "channels": "Direct (markets, home, events, delivery) + indirect non-perishable (retail, restaurants, wholesale); no mail order",
    "label": "Direct: &quot;not certified, labeled, licensed, packaged, regulated, or inspected&quot;; Retail: &quot;made in a home kitchen, is not regulated or inspected and may contain allergens.&quot;",
    "inspectTrain": "None",
    "sources": "<a href=\"https://law.justia.com/codes/wyoming/title-11/chapter-49/section-11-49-103/\">WY Statutes §11-49-103</a>, <a href=\"https://forrager.com/law/wyoming/\">Forrager</a>",
    "details": "Permit: None: Food Freedom Act (W.S. §11-49); no license, inspection, or training needed. Cap: Reported as $250,000/yr by secondary sources <strong>[UNCONFIRMED against statute text directly]</strong>. Products: Non-perishable sellable anywhere incl. retail/wholesale; perishable (dairy fillings, wedding cakes) direct-to-consumer only. Channels: Direct (markets, home, events, delivery) + indirect non-perishable (retail, restaurants, wholesale); no mail order. Label: Direct: &quot;not certified, labeled, licensed, packaged, regulated, or inspected&quot;; Retail: &quot;made in a home kitchen, is not regulated or inspected and may contain allergens.&quot; Inspect/Train: None. Sources: <a href=\"https://law.justia.com/codes/wyoming/title-11/chapter-49/section-11-49-103/\">WY Statutes §11-49-103</a>, <a href=\"https://forrager.com/law/wyoming/\">Forrager</a>"
  },
  {
    "state": "District of Columbia",
    "permit": "<strong>Registration required</strong>: Cottage Food Registry ID/Certificate (<del>$50), Home Occupation Permit, Certified Food Protection Manager cert (</del>$69+$35), pre-op inspection",
    "cap": "None (removed 2020)",
    "products": "Shelf-stable only: no cream/custard/cheese/meat fillings",
    "channels": "Expanded by <strong>D.C. Law 26-7 (eff. 6/10/2025)</strong>: direct sales, retail within DC, online within DC, <strong>and now wholesale to licensed DC food establishments</strong>",
    "label": "Permit/registry #, net weight, allergens, registered-cottage-food-business statement",
    "inspectTrain": "CFPM certification + pre-op home kitchen inspection",
    "sources": "<a href=\"https://dchealth.dc.gov/publication/cottage-food-businesses\">DC Health</a>, <a href=\"https://dcfoodpolicy.org/2026/03/02/cottage-food-act-regulations/\">DC Food Policy Council</a>, <a href=\"https://forrager.com/law/district-of-columbia/\">Forrager</a>",
    "details": "Permit: <strong>Registration required</strong>: Cottage Food Registry ID/Certificate (<del>$50), Home Occupation Permit, Certified Food Protection Manager cert (</del>$69+$35), pre-op inspection. Cap: None (removed 2020). Products: Shelf-stable only: no cream/custard/cheese/meat fillings. Channels: Expanded by <strong>D.C. Law 26-7 (eff. 6/10/2025)</strong>: direct sales, retail within DC, online within DC, <strong>and now wholesale to licensed DC food establishments</strong>. Label: Permit/registry #, net weight, allergens, registered-cottage-food-business statement. Inspect/Train: CFPM certification + pre-op home kitchen inspection. Sources: <a href=\"https://dchealth.dc.gov/publication/cottage-food-businesses\">DC Health</a>, <a href=\"https://dcfoodpolicy.org/2026/03/02/cottage-food-act-regulations/\">DC Food Policy Council</a>, <a href=\"https://forrager.com/law/district-of-columbia/\">Forrager</a>"
  }
];

const GUIDE_HTML = "<h1>How to Start a Legal Home Bakery (2026 Guide)</h1>\n<h3>The complete, honest walkthrough: from &quot;can I even do this?&quot; to your first sale</h3>\n<p><em>By Bakify: the marketplace for cottage and home bakers</em></p>\n<h2>Key takeaways</h2>\n<ul>\n<li>Nearly every state allows you to legally sell home-baked goods under a &quot;cottage food law&quot;: you almost certainly don&#39;t need a commercial kitchen or a restaurant-grade license to start.</li>\n<li>What varies by state is significant: how much you can earn before you need a real food license, what you&#39;re allowed to sell (plain baked goods are usually fine; anything with cream, custard, or fresh dairy filling usually isn&#39;t), and where you can sell it (direct-to-customer only, versus farmers markets, versus retail shelves).</li>\n<li>Getting the legal basics right takes a few hours, not a few months. Getting pricing and labeling right is what actually determines whether the business survives its first year.</li>\n<li>Once you&#39;re set up, the operational bottleneck isn&#39;t baking: it&#39;s order-taking. Most home bakers hit a wall around 10–15 orders a week when spreadsheets and DM threads stop working.</li>\n</ul>\n<h2>What is a home bakery, exactly?</h2>\n<p>A home bakery (also called a cottage bakery or micro-bakery) is a baking business run out of your own residential kitchen, operating under your state&#39;s cottage food law rather than a commercial food-service license. It&#39;s the legal on-ramp almost every professional baker in the country used at some point: including a lot of the accounts you already follow on Instagram.</p>\n<p>The advantage is obvious: no commercial lease, no expensive build-out, no restaurant-grade equipment requirement. The trade-off is equally real: you operate within limits on what you can sell, how much you can earn, and where you can sell it: limits that exist specifically because your kitchen isn&#39;t held to commercial food-safety standards. Those limits aren&#39;t red tape to route around; they&#39;re the actual boundary of what&#39;s legal, and ignoring them is the single most common way new home bakers get themselves into real trouble (a shutdown letter, a fine, or in the worst case a foodborne-illness liability claim with no license to fall back on).</p>\n<h2>Is it legal where you live?</h2>\n<p>Yes, almost certainly: cottage food laws now exist in every U.S. state and D.C. (New Jersey was the last holdout, adopting its law in 2021). But &quot;is it legal&quot; isn&#39;t a yes/no question so much as a &quot;what are the specific rules&quot; question, and the rules genuinely do not transfer across state lines. What worked for a baker you follow in Texas may be flatly illegal in Massachusetts.</p>\n<p>Three things vary state to state, and you need to know your own state&#39;s answer to each before you sell anything:</p>\n<p><strong>1. What you&#39;re allowed to sell.</strong> Almost every state allows &quot;non-potentially-hazardous&quot; baked goods: breads, cookies, cakes with shelf-stable frosting, most fruit pies. Almost every state prohibits anything that needs refrigeration to be safe: cheesecake, custard or cream pies, cream cheese frosting, cream-filled pastries: because these can support bacterial growth outside a commercial cold-chain. A handful of states (Nebraska, Louisiana, Utah under its Food Freedom Act, Tennessee) are meaningfully more permissive here. Don&#39;t assume; check.</p>\n<p><strong>2. How much you can earn.</strong> Most states cap your annual gross cottage-food sales somewhere between $25,000 and $150,000: a few (Wyoming, Missouri, Wisconsin, Tennessee) have no cap at all for baked goods. Cross the cap and you legally need to move into a licensed commercial or &quot;home processor&quot; tier, which usually means a kitchen inspection.</p>\n<p><strong>3. Where you&#39;re allowed to sell.</strong> Some states restrict you to direct, in-person, in-state sales only (no shipping, no third-party delivery). Others allow online orders, farmers markets, or even retail shelf space. This is the rule most new bakers get wrong, because &quot;someone in another state does it this way&quot; is not evidence that it&#39;s legal in yours.</p>\n<p><strong>What you do <em>not</em> need, in most states:</strong> a business degree, a restaurant license, a commercial kitchen, a food truck-style inspection regime, or (in the majority of states) even a fee: many cottage food registrations are free or under $50.</p>\n<p><strong>What you <em>do</em> need, almost everywhere:</strong> to know your state&#39;s specific answer to the three questions above, a compliant label (see below), and: depending on your state: either nothing at all, a free registration, or a modest permit fee and possibly a home kitchen inspection.</p>\n<p><strong>How to find your exact state&#39;s rules:</strong> start with your state&#39;s Department of Agriculture or Department of Health (search &quot;[your state] cottage food law&quot;), and cross-reference with Forrager&#39;s cottage food law database (forrager.com/laws), which tracks all 50 states and updates as laws change. Bakify&#39;s own state-by-state reference (delivered alongside this guide) gives you a plain-English starting point: but cottage food law is one of the more actively-amended corners of state policy, so always confirm anything financially or legally material directly with your state agency before you rely on it.</p>\n<h2>Setting up your kitchen</h2>\n<p>You don&#39;t need a second kitchen or commercial equipment to start. You do need:</p>\n<ul>\n<li>A kitchen that&#39;s actually usable for regular production: enough counter space, oven capacity, and storage that you&#39;re not fighting your own household for space during a rush.</li>\n<li>To follow your state&#39;s specific kitchen rules, if any (some require a two-compartment sink or dishwasher, a working smoke detector, no pets present during production, or a passing well-water test if you&#39;re not on municipal water).</li>\n<li>Basic food-safety habits regardless of what your state requires on paper: consistent handwashing, allergen-aware surface cleaning between different products, and accurate batch/date tracking.</li>\n<li>If your state requires a home kitchen inspection (several do, including Massachusetts, Connecticut, Delaware, Washington, North Carolina, and Pennsylvania), schedule it early: inspection backlogs can run weeks, and you can&#39;t legally sell until it&#39;s passed.</li>\n</ul>\n<h2>Pricing your baked goods</h2>\n<p>The single most common financial mistake new home bakers make is pricing based on ingredient cost alone and forgetting to pay themselves for the hours. A dozen cupcakes that cost $4 in ingredients and take 90 minutes to make, decorate, and package is not a $10 product: it&#39;s closer to $30–40 once your labor is priced at even a modest hourly rate.</p>\n<p>A workable formula: <strong>(ingredient cost + packaging cost) + (your hours × your target hourly rate) + a margin for waste, tests, and platform/payment fees.</strong> Round up, not down. Charging your neighbors a rate that reflects real labor value feels uncomfortable at first: most home bakers underprice by 30–50% in their first few months: but underpricing is what turns a promising side business into an unpaid second job.</p>\n<p>Pre-order and batch-based models (bake to a confirmed order, not to a guess) protect this math directly: you&#39;re not absorbing the cost of unsold speculative inventory, and you can plan your week&#39;s baking around known demand instead of hoping.</p>\n<h2>Labeling requirements</h2>\n<p>Every state requires a compliant label before you sell: this is the one area where &quot;close enough&quot; isn&#39;t good enough, because it&#39;s also a food-safety and allergen-disclosure requirement, not just a bureaucratic formality. See the companion <strong>Cottage Food Label Checklist</strong> for the full breakdown, but at minimum, expect to need: a clear product name, a full ingredient list in descending order by weight, a net weight/volume, your business name and address, an allergen declaration, and your state&#39;s specific &quot;made in a home kitchen, not subject to routine inspection&quot;-style disclosure statement (the exact wording is state-specific: don&#39;t copy another state&#39;s language).</p>\n<p>The most common way labels go wrong isn&#39;t at launch: it&#39;s months later, when a recipe quietly changes (a new frosting supplier, a tweak to reduce cost) and the printed label stack doesn&#39;t get updated. Treat your ingredient list as a living document tied to the actual recipe, and re-check your label anytime a recipe changes, not just when you first print it.</p>\n<h2>Marketing your home bakery</h2>\n<p>Before you need Instagram, you need your existing network: most home bakeries&#39; first ten customers come from word of mouth, not social media. Once you&#39;ve got a handful of repeat customers and a couple of products people actually rave about, that&#39;s the point where a platform like Instagram (see Bakify&#39;s Instagram Growth Strategy resources) starts compounding rather than starting from zero. Photograph your best work consistently, be upfront in captions about pickup/delivery logistics and lead times, and let happy customers do a meaningful share of your marketing for you through reviews and repeat orders.</p>\n<h2>When you hit the order wall</h2>\n<p>Almost every home baker hits the same operational bottleneck around 10–15 orders a week: a spreadsheet plus a string of Instagram DMs and text messages stops being able to track who ordered what, when it&#39;s due, and whether they&#39;ve paid. This isn&#39;t a sign you&#39;re doing something wrong: it&#39;s a predictable growth stage. The fix is a system built for pre-orders (clear cutoffs, batch production windows, and a single source of truth for order status and payment) rather than trying to manage growing order volume by memory. This is exactly the gap Bakify is built to close once we launch.</p>\n<h2>Common mistakes to avoid</h2>\n<ul>\n<li>Assuming a rule from a friend&#39;s state, a YouTube video, or a national blog applies in your state without checking.</li>\n<li>Selling a product your state classifies as potentially hazardous (custard, cream cheese frosting, cheesecake) because &quot;everyone does it.&quot;</li>\n<li>Skipping the label disclaimer, or copying another state&#39;s exact wording instead of your own state&#39;s.</li>\n<li>Pricing to match what a neighbor &quot;would pay&quot; instead of what your labor and ingredients actually cost.</li>\n<li>Baking speculatively (&quot;I&#39;ll make extra and see who buys&quot;) instead of confirming orders first: this is the fastest way to bury a home bakery in unsold inventory and wasted ingredient cost.</li>\n<li>Letting your label fall out of sync with your actual recipe after the first print run.</li>\n</ul>\n<h2>FAQ</h2>\n<p><strong>Do I need an LLC to sell under a cottage food law?</strong> No: most home bakers start as a sole proprietor. An LLC can make sense later for liability protection as volume grows, but it isn&#39;t a legal prerequisite to sell under most states&#39; cottage food laws.</p>\n<p><strong>Can I ship my baked goods to another state?</strong> In most states, no: cottage food laws typically restrict you to in-state, direct sales, and interstate shipment of a cottage-food product can trigger both your home state&#39;s and the destination state&#39;s rules. Check both before you ship.</p>\n<p><strong>Do I need insurance?</strong> It&#39;s not legally required in most states to register as a cottage food operation, but general liability or product liability coverage (sometimes available cheaply through cottage-food associations) is worth pricing out once you&#39;re selling regularly: a foodborne-illness claim without any coverage can be a business-ending event.</p>\n<p><strong>What if I want to sell something my state doesn&#39;t allow (like custard or cheesecake)?</strong> You&#39;d need to either move into a licensed commercial/home-processor tier (varies by state: often requires a kitchen inspection) or produce that specific product in a licensed commercial kitchen instead of your home. Selling it anyway under a cottage food registration is the most common way home bakers end up with a compliance problem.</p>\n<p><strong>How do I actually find my state&#39;s current rules?</strong> Search &quot;[your state] cottage food law&quot; and go to the .gov result first, then cross-check with Forrager&#39;s database (forrager.com/laws). See Bakify&#39;s state-by-state reference for a starting point on all 50 states + D.C.</p>\n<hr>\n<p><em>This guide is educational, not legal advice. Cottage food law changes frequently: always confirm current requirements directly with your state&#39;s Department of Agriculture or Health before making business decisions.</em></p>\n";

const LABEL_HTML = "<h1>Cottage Food Label Checklist</h1>\n<h3>The 8 things almost every state requires on a home-baked product label</h3>\n<p><em>By Bakify: the marketplace for cottage and home bakers</em></p>\n<p>Cottage food labeling requirements vary by state in the details, but nearly every state&#39;s law requires some version of these eight elements. Treat this as your baseline, then check Bakify&#39;s state-by-state Cottage Food Law Reference for your specific state&#39;s exact wording and any extras (batch codes, permit numbers, net-weight format, etc.).</p>\n<p><strong>1. Product name.</strong> A clear, specific name that tells the customer exactly what they&#39;re buying: &quot;Chocolate Chip Cookies,&quot; not just &quot;Cookies,&quot; and definitely not a cutesy name with no description anywhere on the label.</p>\n<p><strong>2. Ingredient list, descending order by weight.</strong> List every ingredient from most to least by weight, using common names (not just brand names), and make sure every sub-ingredient of a component (like what&#39;s actually in your &quot;vanilla extract&quot; or a pre-made mix) is accounted for.</p>\n<p><strong>3. Net weight or volume.</strong> The actual amount the customer receives, measured after baking/packaging: not an estimate. Most states want this in both U.S. and metric units (e.g., &quot;Net Wt. 8 oz (227g)&quot;).</p>\n<p><strong>4. Your business name and address.</strong> So a customer (or a regulator) can identify and contact you. Some states allow a registration/permit number in place of your home address if you&#39;ve registered through a program that offers that option: worth checking, since not every home baker wants their home address on every package.</p>\n<p><strong>5. Allergen declaration.</strong> A &quot;Contains&quot; statement listing any of the major allergens present: milk, egg, wheat, tree nuts, peanuts, soy, fish, shellfish, sesame. Get this from your actual recipe, not from memory, and re-check it every time a recipe or supplier changes: this is the single highest-stakes item on the label.</p>\n<p><strong>6. Your state&#39;s specific cottage food disclosure statement.</strong> Nearly every state requires some version of &quot;made in a home kitchen that is not inspected/licensed by [state agency]&quot;: but the exact required wording is different state to state, and using the wrong state&#39;s language (copied from a template or another baker&#39;s label) can itself be a compliance violation. Use your own state&#39;s exact required text.</p>\n<p><strong>7. Production or best-by date.</strong> Technically optional in some states, required in others, but worth including everywhere: it gives customers a clear sense of shelf life and gives you batch traceability if something ever needs to be tracked back.</p>\n<p><strong>8. Registration or permit number, if your state issues one.</strong> Several states (Illinois, Arizona, Delaware, Washington, D.C., and others) require your registration/permit number to appear directly on the label, not just on file with the agency.</p>\n<h2>The &quot;label drift&quot; problem</h2>\n<p>Labels rarely go wrong on day one: they go wrong months later, when a recipe quietly evolves (a new frosting recipe, a cheaper flour supplier, a swapped-in ingredient to save cost) and the printed label stack doesn&#39;t get updated to match. This is especially dangerous on the allergen line, since an undetected ingredient swap can turn an accurate allergen statement into an inaccurate: and potentially dangerous: one.</p>\n<p><strong>How to avoid it:</strong> treat your ingredient list as a living document tied to your actual current recipe, not a one-time PDF you printed at launch. Before each new label print run, do a quick side-by-side check: does this label match exactly what&#39;s going into this batch, today?</p>\n<h2>Before you print: final check</h2>\n<ul>\n<li>Does the ingredient list match today&#39;s actual recipe, not an earlier version?</li>\n<li>Is every allergen actually present in the recipe declared?</li>\n<li>Does the disclosure statement use your state&#39;s exact required wording (not another state&#39;s)?</li>\n<li>Is the net weight accurate for this specific batch, not a rough average?</li>\n<li>If your state requires it, is your registration/permit number on the label itself?</li>\n</ul>\n<hr>\n<p><em>This checklist is educational, not legal advice. Always confirm your state&#39;s exact labeling requirements with your Department of Agriculture or Health: see Bakify&#39;s state-by-state Cottage Food Law Reference as a starting point.</em></p>\n";
